language: node_js
node_js:
  - "16.14.2"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project fashion-hunter-27637 --token "$FIREBASE_TOKEN"
